AOS-167 Removed jakarta from pom.xml, otherwise swagger failed to load.
felleslosninger/eid-statistikk-inndata-api pull request #35
Opened 2022-08-18 11:35 UTC by kometen

Fjernede jakarta fra pom.xml, så swagger vises igen. Har POST'et data via token fra maskinporten. Har tilsyneladende ikke behov for jakarta.

2022-08-18 11:48 UTC, kons-jaf requested changes
Jeg tror ikke det blir rett å være avhengig av Glassfish for å få riktig JAXB-klasser.

2022-08-18 11:48 UTC, kons-jaf commented on pom.xml
> +            <version>4.0.0</version>
Jeg tror du var på rett spor først. Dette funket for meg:
```suggestion
<groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>${jaxb.version}</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-ri</artifactId>
            <version>${jaxb.version}</version>
```

2022-08-18 13:27 UTC, kometen commented
Har fjernet glassfish-jaxb. Bygger fint uden, kan POST'e via maskinporten.

2022-08-19 05:25 UTC, kons-jaf approved these changes

2022-08-19 06:08 UTC, merged